# Generated by Django 4.2.16 on 2026-08-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtrusionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('PIECES_WEIGHT', 'Pieces to Weight'), ('THICKNESS', 'Thickness Calculation'), ('TAKEUP_SPEED', 'Take-up Speed Adjustment'), ('ROLL_RADIUS', 'Roll Radius/Mass'), ('ROLL_RADIUS_FROM_MASS', 'Roll Radius from Mass'), ('FILM_LENGTH', 'Film Length from Weight'), ('WEIGHT_FROM_LENGTH', 'Weight from Length'), ('PRODUCTION_TIME', 'Production Time'), ('BUR_DDR', 'Blown Film Ratios'), ('TENSILE', 'Tensile Strength'), ('ELONGATION', 'Percent Elongation'), ('COF', 'Coefficient of Friction'), ('DART_IMPACT', 'Dart Impact'), ('GAUGE_VARIATION', 'Gauge Variation'), ('COMPOSITE_DENSITY', 'Composite Density'), ('YIELD_BASIS', 'Yield & Basis Weight'), ('LAYER_DISTRIBUTION_3', '3-Layer Distribution'), ('LAYER_DISTRIBUTION_5', '5-Layer Distribution'), ('MASTERBATCH_DOSING', 'Masterbatch Dosing'), ('REGRIND_BLEND', 'Regrind/Recycled Blend'), ('SPECIFIC_OUTPUT', 'Specific Output Rate'), ('NECK_IN_DRAW', 'Neck-in / Draw Ratio'), ('PUNCTURE_ENERGY', 'Puncture Resistance / Impact Energy'), ('SECANT_MODULUS', 'Secant Modulus'), ('WASTE_PERCENT', 'Scrap/Waste Percentage'), ('BARRIER_NORMALIZATION', 'Barrier Property Normalization')], max_length=25)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine_name', models.CharField(blank=True, choices=[('RAJOO_01', 'Rajoo 01'), ('RAJOO_02', 'Rajoo 02'), ('RAJOO_03', 'Rajoo 03'), ('MAMATA_01', 'Mamata 01'), ('MAMATA_02', 'Mamata 02'), ('WINDSOR', 'Windsor'), ('JINMING', 'Jinming'), ('PP_01', 'PP 01'), ('PP_02', 'PP 02'), ('TAIWAN_01', 'Taiwan 01'), ('TAIWAN_02', 'Taiwan 02'), ('TAIWAN_03', 'Taiwan 03'), ('TAIWAN_04', 'Taiwan 04'), ('TAIWAN_05', 'Taiwan 05'), ('TAIWAN_06', 'Taiwan 06'), ('HEMINGSTON_01', 'Hemingston 01'), ('HEMINGSTON_02', 'Hemingston 02'), ('HEMINGSTON_03', 'Hemingston 03'), ('HEMINGSTON_04', 'Hemingston 04'), ('GURUCHARANI_01', 'Gurucharani 01'), ('GURUCHARANI_02', 'Gurucharani 02'), ('GURUCHARANI_03', 'Gurucharani 03'), ('CHINA_01', 'China 01'), ('CHINA_02', 'China 02'), ('CHINA_03', 'China 03'), ('CONCORD', 'Concord'), ('SHOWMAN', 'Showman')], max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order_name', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThicknessMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('thickness', models.FloatField()),
                ('measurement_order', models.IntegerField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thickness_measurements', to='extrusion.extrusioncalculation')),
            ],
            options={
                'ordering': ['measurement_order'],
            },
        ),
    ]
