# Generated by Django 4.2.16 on 2026-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrusioncalculation',
            name='calculation_type',
            field=models.CharField(choices=[('PIECES_WEIGHT', 'Pieces to Weight'), ('THICKNESS', 'Thickness Calculation'), ('TAKEUP_SPEED', 'Take-up Speed Adjustment'), ('ROLL_RADIUS', 'Roll Radius/Mass'), ('ROLL_RADIUS_FROM_MASS', 'Roll Radius from Mass'), ('FILM_LENGTH', 'Film Length from Weight'), ('WEIGHT_FROM_LENGTH', 'Weight from Length'), ('PRODUCTION_TIME', 'Production Time'), ('BUR_DDR', 'Blown Film Ratios'), ('TENSILE', 'Tensile Strength'), ('ELONGATION', 'Percent Elongation'), ('COF', 'Coefficient of Friction'), ('DART_IMPACT', 'Dart Impact'), ('GAUGE_VARIATION', 'Gauge Variation'), ('COMPOSITE_DENSITY', 'Composite Density'), ('YIELD_BASIS', 'Yield & Basis Weight'), ('LAYER_DISTRIBUTION_3', '3-Layer Distribution'), ('LAYER_DISTRIBUTION_5', '5-Layer Distribution')], max_length=25),
        ),
    ]
