# Generated by Django 4.2.16 on 2026-07-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrusion', '0003_alter_extrusioncalculation_calculation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thicknessmeasurement',
            old_name='thickness_microns',
            new_name='thickness',
        ),
        migrations.AddField(
            model_name='extrusioncalculation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extrusioncalculation',
            name='machine_name',
            field=models.CharField(blank=True, choices=[('RAJOO_01', 'Rajoo 01'), ('RAJOO_02', 'Rajoo 02'), ('RAJOO_03', 'Rajoo 03'), ('MAMATA_01', 'Mamata 01'), ('MAMATA_02', 'Mamata 02'), ('WINDSOR', 'Windsor'), ('JINMING', 'Jinming'), ('PP_01', 'PP 01'), ('PP_02', 'PP 02'), ('TAIWAN_01', 'Taiwan 01'), ('TAIWAN_02', 'Taiwan 02'), ('TAIWAN_03', 'Taiwan 03'), ('TAIWAN_04', 'Taiwan 04'), ('TAIWAN_05', 'Taiwan 05'), ('TAIWAN_06', 'Taiwan 06'), ('HEMINGSTON_01', 'Hemingston 01'), ('HEMINGSTON_02', 'Hemingston 02'), ('HEMINGSTON_03', 'Hemingston 03'), ('HEMINGSTON_04', 'Hemingston 04'), ('GURUCHARANI_01', 'Gurucharani 01'), ('GURUCHARANI_02', 'Gurucharani 02'), ('GURUCHARANI_03', 'Gurucharani 03'), ('CHINA_01', 'China 01'), ('CHINA_02', 'China 02'), ('CHINA_03', 'China 03'), ('CONCORD', 'Concord'), ('SHOWMAN', 'Showman')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extrusioncalculation',
            name='order_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
