# Generated by Django 5.2.4 on 2026-09-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('qc_technician', 'QC Technician'), ('sales_representative', 'Sales Representative'), ('engineer', 'Engineer'), ('accountant', 'Accountant'), ('auditor', 'Auditor'), ('procurement officer', 'Procurement Officer'), ('store manager', 'Store Manager'), ('other', 'Other')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='section',
            field=models.CharField(choices=[('extrusion', 'Extrusion'), ('printing', 'Printing'), ('lamination', 'Lamination'), ('slitting', 'Slitting'), ('bag_making', 'Bag Making'), ('quality_control', 'Quality Control'), ('maintenance', 'Maintenance'), ('sales', 'Sales'), ('accounts and finance', 'Accounts and Finance'), ('procurement', 'Procurement'), ('stores', 'Stores'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
