# Generated by Django 4.2.16 on 2026-08-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=50)),
                ('density', models.FloatField(help_text='Density in g/cm³')),
                ('wall_thickness_mm', models.FloatField(default=1.5, help_text='Typical wall thickness in mm')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SlittingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('ROLL_MASS', 'Roll Mass from Diameter'), ('ROLL_DIAMETER', 'Roll Diameter from Mass'), ('SLITTING_TIME', 'Slitting Time'), ('PRODUCTION_EFFICIENCY', 'Production Efficiency'), ('PRODUCTION_RATE', 'Production Rate'), ('YIELD_CALCULATION', 'Yield Calculation'), ('FILM_LENGTH', 'Film Length from Mass'), ('KNIFE_LAYOUT', 'Knife Layout / Slit Count'), ('ROLLS_FROM_MASS', 'Rolls from Total Mass'), ('TENSION_TAPER', 'Winding Tension Taper'), ('WIND_QUALITY', 'Wind Quality Check'), ('DOWNTIME_BREAKDOWN', 'Downtime Breakdown'), ('WASTE_ALLOWANCE', 'Waste Allowance Planning')], max_length=30)),
                ('machine_name', models.CharField(blank=True, choices=[('HCI_01', 'HCI 01'), ('HCI_02', 'HCI 02'), ('BIMEC', 'Bimec'), ('NISSI_02', 'Nissi 02'), ('NISSI_03', 'Nissi 03'), ('FADIA', 'Fadia')], max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('order_name', models.CharField(blank=True, max_length=150)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('core_weight_source', models.CharField(blank=True, max_length=20, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlittingLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField()),
                ('thickness_unit', models.CharField(default='micron', max_length=10)),
                ('layer_order', models.IntegerField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='slitting.slittingcalculation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
            ],
            options={
                'ordering': ['layer_order'],
            },
        ),
    ]
