# Generated by Django 5.2.4 on 2025-12-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slitting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slittingcalculation',
            name='core_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slittingcalculation',
            name='gross_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slittingcalculation',
            name='includes_core_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slittingcalculation',
            name='net_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slittingcalculation',
            name='calculation_type',
            field=models.CharField(choices=[('ROLL_MASS', 'Roll Mass from Diameter'), ('ROLL_DIAMETER', 'Roll Diameter from Mass'), ('SLITTING_TIME', 'Slitting Time'), ('PRODUCTION_EFFICIENCY', 'Production Efficiency'), ('PRODUCTION_RATE', 'Production Rate'), ('YIELD_CALCULATION', 'Yield Calculation'), ('CORE_WEIGHT', 'Core Weight Calculation')], max_length=30),
        ),
    ]
