# Generated by Django 4.2.16 on 2026-07-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slitting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slittingcalculation',
            name='calculation_type',
            field=models.CharField(choices=[('ROLL_MASS', 'Roll Mass from Diameter'), ('ROLL_DIAMETER', 'Roll Diameter from Mass'), ('SLITTING_TIME', 'Slitting Time'), ('PRODUCTION_EFFICIENCY', 'Production Efficiency'), ('PRODUCTION_RATE', 'Production Rate'), ('YIELD_CALCULATION', 'Yield Calculation'), ('FILM_LENGTH', 'Film Length from Mass'), ('KNIFE_LAYOUT', 'Knife Layout / Slit Count'), ('ROLLS_FROM_MASS', 'Rolls from Total Mass'), ('TENSION_TAPER', 'Winding Tension Taper'), ('WIND_QUALITY', 'Wind Quality Check'), ('DOWNTIME_BREAKDOWN', 'Downtime Breakdown'), ('WASTE_ALLOWANCE', 'Waste Allowance Planning')], max_length=30),
        ),
    ]
