# Generated by Django 5.2.4 on 2025-12-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slitting', '0002_slittingcalculation_core_weight_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=50)),
                ('density', models.FloatField(help_text='Density in g/cm³')),
                ('wall_thickness_mm', models.FloatField(default=1.5, help_text='Typical wall thickness in mm')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='slittingcalculation',
            name='core_weight_kg',
        ),
        migrations.RemoveField(
            model_name='slittingcalculation',
            name='gross_weight_kg',
        ),
        migrations.RemoveField(
            model_name='slittingcalculation',
            name='includes_core_weight',
        ),
        migrations.RemoveField(
            model_name='slittingcalculation',
            name='net_weight_kg',
        ),
        migrations.AddField(
            model_name='slittingcalculation',
            name='core_weight_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='slittingcalculation',
            name='calculation_type',
            field=models.CharField(choices=[('ROLL_MASS', 'Roll Mass from Diameter'), ('ROLL_DIAMETER', 'Roll Diameter from Mass'), ('SLITTING_TIME', 'Slitting Time'), ('PRODUCTION_EFFICIENCY', 'Production Efficiency'), ('PRODUCTION_RATE', 'Production Rate'), ('YIELD_CALCULATION', 'Yield Calculation')], max_length=30),
        ),
    ]
