# Generated by Django 4.2.16 on 2026-07-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slitting', '0002_alter_slittingcalculation_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slittingcalculation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='slittingcalculation',
            name='machine_name',
            field=models.CharField(blank=True, choices=[('HCI_01', 'HCI 01'), ('HCI_02', 'HCI 02'), ('BIMEC', 'Bimec'), ('NISSI_02', 'Nissi 02'), ('NISSI_03', 'Nissi 03'), ('FADIA', 'Fadia')], max_length=20),
        ),
        migrations.AddField(
            model_name='slittingcalculation',
            name='order_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
