# Generated by Django 4.2.16 on 2026-07-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminationcalculation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='laminationcalculation',
            name='job_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='laminationcalculation',
            name='machine_name',
            field=models.CharField(blank=True, choices=[('UFLEX', 'Uflex'), ('CENTER', 'Center'), ('SIMPLEX', 'Simplex'), ('FADIA', 'Fadia')], max_length=20),
        ),
    ]
