# Generated by Django 4.2.16 on 2026-08-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g. "Grains & Cereals", "Powders", "Fertilizers & Chemicals", "Other"', max_length=50)),
                ('density_min_kg_m3', models.FloatField()),
                ('density_max_kg_m3', models.FloatField()),
                ('density_typical_kg_m3', models.FloatField(help_text='Midpoint of min/max - used as the default')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CutoutGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "D Punch (30mm x 75mm)"', max_length=100)),
                ('geometry_type', models.CharField(help_text='Free-text category tag, e.g. "D_PUNCH" or "VEST_BAG" - used for grouping/filtering in the UI', max_length=50)),
                ('calibration_material', models.CharField(help_text='Material used when this geometry was calibrated', max_length=100)),
                ('density_g_cm3', models.FloatField(help_text='Density (rho) used at calibration - editable if confirmed later')),
                ('layers', models.IntegerField(default=2, help_text='Number of film layers (L) - normally 2')),
                ('area_cm2', models.FloatField(help_text='Stored, reusable effective area (A) - back-calculated once, then fixed')),
                ('calibration_thickness_um', models.FloatField(blank=True, help_text='Thickness used for the calibration sample, for reference', null=True)),
                ('calibration_mass_g', models.FloatField(blank=True, help_text='Measured sample mass used for the back-calculation, for reference', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['geometry_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BagMakingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('PIECES_WEIGHT', 'Pieces ↔ Weight'), ('PACKET_WEIGHT', 'Packet Weight'), ('BUNDLE_WEIGHT', 'Bundle/Bale Weight'), ('PRODUCTION_TIME', 'Production Time'), ('YIELD_EFFICIENCY', 'Yield & Efficiency'), ('BAG_CAPACITY', 'Bag Fill Volume/Capacity'), ('ROLL_REQUIREMENT', 'Bags per Roll / Roll Requirement'), ('SEAL_STRENGTH', 'Heat Seal Strength')], max_length=20)),
                ('bag_type', models.CharField(choices=[('FLAT_SHEET', 'Flat Sheet Bag'), ('TUBULAR', 'Tubular Bag'), ('GUSSETED_SIDE', 'Side Gusseted Bag'), ('GUSSETED_BOTTOM', 'Bottom Gusseted Bag'), ('TUBULAR_WITH_FLAP', 'Tubular Bag with Flap'), ('LAMINATED_FLAT', 'Laminated Flat Bag'), ('LAMINATED_TUBULAR', 'Laminated Tubular Bag'), ('LAMINATED_GUSSETED_SIDE', 'Laminated Side Gusseted Bag'), ('LAMINATED_GUSSETED_BOTTOM', 'Laminated Bottom Gusseted Bag'), ('LAMINATED_TUBULAR_FLAP', 'Laminated Tubular with Flap'), ('GUSSETED_BOTTOM_FLAP', 'Bottom Gusseted Bag with Flap'), ('LAMINATED_GUSSETED_BOTTOM_FLAP', 'Laminated Bottom Gusseted with Flap')], max_length=30)),
                ('addon_type', models.CharField(choices=[('NONE', 'No Add-ons'), ('ZIPPER', 'Zipper Only'), ('HANDLES', 'Handles Only'), ('BOTH', 'Zipper and Handles')], default='NONE', max_length=10)),
                ('machine_name', models.CharField(blank=True, choices=[('SIDE_SEAL_01', 'Side Seal 01'), ('SIDE_SEAL_02', 'Side Seal 02'), ('SIDE_SEAL_03', 'Side Seal 03'), ('SIDE_SEAL_04', 'Side Seal 04'), ('SIDE_SEAL_05', 'Side Seal 05'), ('SIDE_SEAL_06', 'Side Seal 06'), ('SIDE_SEAL_07', 'Side Seal 07'), ('SIDE_SEAL_08', 'Side Seal 08'), ('SIDE_SEAL_09', 'Side Seal 09'), ('SIDE_SEAL_10', 'Side Seal 10'), ('SIDE_SEAL_11', 'Side Seal 11'), ('SIDE_SEAL_12', 'Side Seal 12'), ('SIDE_SEAL_13', 'Side Seal 13'), ('SIDE_SEAL_14', 'Side Seal 14'), ('SIDE_SEAL_15', 'Side Seal 15'), ('SIDE_SEAL_16', 'Side Seal 16'), ('SIDE_SEAL_17', 'Side Seal 17'), ('SIDE_SEAL_18', 'Side Seal 18'), ('SIDE_SEAL_19', 'Side Seal 19'), ('SIDE_SEAL_20', 'Side Seal 20'), ('SIDE_SEAL_21', 'Side Seal 21'), ('SIDE_SEAL_22', 'Side Seal 22'), ('SIDE_SEAL_23', 'Side Seal 23'), ('SIDE_SEAL_24', 'Side Seal 24'), ('SIDE_SEAL_25', 'Side Seal 25'), ('SIDE_SEAL_26', 'Side Seal 26'), ('SIDE_SEAL_27', 'Side Seal 27'), ('SIDE_SEAL_28', 'Side Seal 28'), ('SIDE_SEAL_29', 'Side Seal 29'), ('SIDE_SEAL_30', 'Side Seal 30'), ('SIDE_SEAL_31', 'Side Seal 31'), ('SIDE_SEAL_32', 'Side Seal 32'), ('SIDE_SEAL_33', 'Side Seal 33'), ('SIDE_SEAL_34', 'Side Seal 34'), ('SIDE_SEAL_35', 'Side Seal 35'), ('SIDE_SEAL_36', 'Side Seal 36'), ('SIDE_SEAL_37', 'Side Seal 37'), ('BOTTOM_SEAL_01', 'Bottom Seal 01'), ('BOTTOM_SEAL_02', 'Bottom Seal 02'), ('BOTTOM_SEAL_03', 'Bottom Seal 03'), ('BOTTOM_SEAL_04', 'Bottom Seal 04'), ('BOTTOM_SEAL_05', 'Bottom Seal 05'), ('BOTTOM_SEAL_06', 'Bottom Seal 06'), ('BOTTOM_SEAL_07', 'Bottom Seal 07'), ('BOTTOM_SEAL_08', 'Bottom Seal 08'), ('BOTTOM_SEAL_09', 'Bottom Seal 09'), ('BOTTOM_SEAL_10', 'Bottom Seal 10'), ('BOTTOM_SEAL_11', 'Bottom Seal 11'), ('BOTTOM_SEAL_12', 'Bottom Seal 12'), ('BOTTOM_SEAL_13', 'Bottom Seal 13'), ('BOTTOM_SEAL_14', 'Bottom Seal 14'), ('BOTTOM_SEAL_15', 'Bottom Seal 15'), ('BOTTOM_SEAL_16', 'Bottom Seal 16'), ('BOTTOM_SEAL_17', 'Bottom Seal 17'), ('BOTTOM_SEAL_18', 'Bottom Seal 18'), ('BOTTOM_SEAL_19', 'Bottom Seal 19'), ('POUCH_01', 'Pouch 01'), ('POUCH_02', 'Pouch 02'), ('POUCH_03', 'Pouch 03'), ('POUCH_04', 'Pouch 04'), ('POUCH_05', 'Pouch 05'), ('POUCH_06', 'Pouch 06'), ('FOLDER_01', 'Folder 01'), ('FOLDER_02', 'Folder 02'), ('FOLDER_03', 'Folder 03'), ('VEST_BAG_01', 'Vest Bag 01'), ('VEST_BAG_02', 'Vest Bag 02'), ('VEST_BAG_03', 'Vest Bag 03'), ('VEST_BAG_04', 'Vest Bag 04'), ('VEST_BAG_05', 'Vest Bag 05'), ('VEST_BAG_06', 'Vest Bag 06'), ('SPOUT_01', 'Spout 01'), ('SPOUT_02', 'Spout 02'), ('BREATHER_VENT_01', 'Breather/Vent 01'), ('BREATHER_VENT_02', 'Breather/Vent 02')], max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('order_name', models.CharField(blank=True, max_length=150)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BagLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField()),
                ('thickness_unit', models.CharField(default='micron', max_length=10)),
                ('layer_order', models.IntegerField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='bag_making.bagmakingcalculation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
            ],
            options={
                'ordering': ['layer_order'],
            },
        ),
        migrations.CreateModel(
            name='AddonComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('ZIPPER', 'Zipper'), ('HANDLE', 'Handle')], max_length=10)),
                ('weight_per_piece', models.FloatField(help_text='Weight in grams per piece')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='bag_making.bagmakingcalculation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
            ],
        ),
    ]
