# Generated by Django 5.2.4 on 2026-03-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_making', '0001_initial'),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagmakingcalculation',
            name='handle_type',
            field=models.CharField(choices=[('NONE', 'No Handle'), ('DIE_CUT', 'Die Cut Handle'), ('PUNCH', 'Punch Handle'), ('LOOP', 'Loop Handle'), ('DRAWCORD', 'Drawcord')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='bagmakingcalculation',
            name='handle_weight_per_piece',
            field=models.FloatField(blank=True, help_text='Handle weight in grams per piece', null=True),
        ),
        migrations.AddField(
            model_name='bagmakingcalculation',
            name='zipper_length',
            field=models.FloatField(blank=True, help_text='Zipper length in selected unit', null=True),
        ),
        migrations.AddField(
            model_name='bagmakingcalculation',
            name='zipper_type',
            field=models.CharField(choices=[('NONE', 'No Zipper'), ('STANDARD', 'Standard Zipper'), ('PRESS', 'Press Lock Zipper'), ('SLIDER', 'Slider Zipper')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='bagmakingcalculation',
            name='zipper_weight_per_meter',
            field=models.FloatField(blank=True, help_text='Zipper weight in grams per meter', null=True),
        ),
        migrations.AlterField(
            model_name='bagmakingcalculation',
            name='bag_type',
            field=models.CharField(choices=[('FLAT_SHEET', 'Flat Sheet Bag'), ('TUBULAR', 'Tubular Bag'), ('SIDE_GUSSETED', 'Side Gusseted Bag'), ('BOTTOM_GUSSETED', 'Bottom Gusseted Bag'), ('FLAP', 'Flap Bag'), ('LAMINATED_FLAT', 'Laminated Flat Bag'), ('LAMINATED_TUBULAR', 'Laminated Tubular Bag'), ('LAMINATED_SIDE_GUSSETED', 'Laminated Side Gusseted Bag'), ('LAMINATED_BOTTOM_GUSSETED', 'Laminated Bottom Gusseted Bag'), ('LAMINATED_FLAP', 'Laminated Flap Bag')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bagmakingcalculation',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial'),
        ),
        migrations.CreateModel(
            name='BagAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_type', models.CharField(choices=[('ZIPPER', 'Zipper'), ('HANDLE', 'Handle'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('weight_per_unit', models.FloatField(help_text='Weight in grams per unit (meter or piece)')),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(default='meter', max_length=20)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='bag_making.bagmakingcalculation')),
            ],
        ),
    ]
