# Generated by Django 5.2.4 on 2026-03-13 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_making', '0002_bagmakingcalculation_handle_type_and_more'),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagmakingcalculation',
            name='handle_type',
        ),
        migrations.RemoveField(
            model_name='bagmakingcalculation',
            name='handle_weight_per_piece',
        ),
        migrations.RemoveField(
            model_name='bagmakingcalculation',
            name='zipper_length',
        ),
        migrations.RemoveField(
            model_name='bagmakingcalculation',
            name='zipper_type',
        ),
        migrations.RemoveField(
            model_name='bagmakingcalculation',
            name='zipper_weight_per_meter',
        ),
        migrations.AlterField(
            model_name='bagmakingcalculation',
            name='bag_type',
            field=models.CharField(choices=[('FLAT_SHEET', 'Flat Sheet Bag'), ('TUBULAR', 'Tubular Bag'), ('SIDE_GUSSETED', 'Side Gusseted Bag'), ('BOTTOM_GUSSETED', 'Bottom Gusseted Bag'), ('FLAP_BAG', 'Flap Bag'), ('LAMINATED_FLAT', 'Laminated Flat Bag'), ('LAMINATED_TUBULAR', 'Laminated Tubular Bag'), ('LAMINATED_SIDE_GUSSETED', 'Laminated Side Gusseted Bag'), ('LAMINATED_BOTTOM_GUSSETED', 'Laminated Bottom Gusseted Bag'), ('LAMINATED_FLAP', 'Laminated Flap Bag')], max_length=25),
        ),
        migrations.AlterField(
            model_name='bagmakingcalculation',
            name='calculation_type',
            field=models.CharField(choices=[('PIECES_WEIGHT', 'Pieces ↔ Weight'), ('PACKET_WEIGHT', 'Packet Weight'), ('BUNDLE_WEIGHT', 'Bundle/Bale Weight'), ('PRODUCTION_TIME', 'Production Time'), ('YIELD_EFFICIENCY', 'Yield & Efficiency'), ('ZIPPER_WEIGHT', 'Zipper Weight'), ('HANDLE_WEIGHT', 'Handle Weight')], max_length=20),
        ),
        migrations.CreateModel(
            name='BagComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('ZIPPER', 'Zipper'), ('HANDLE', 'Handle'), ('DIE_CUT', 'Die Cut Handle'), ('REINFORCEMENT', 'Reinforcement Patch')], max_length=20)),
                ('length', models.FloatField()),
                ('length_unit', models.CharField(default='cm', max_length=10)),
                ('width', models.FloatField(blank=True, null=True)),
                ('width_unit', models.CharField(default='cm', max_length=10)),
                ('zipper_type', models.CharField(blank=True, choices=[('PRESS', 'Press Seal'), ('SLIDER', 'Slider Zipper'), ('TWIST', 'Twist Tie')], max_length=20, null=True)),
                ('weight_grams', models.FloatField(blank=True, null=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bag_making.bagmakingcalculation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
            ],
            options={
                'ordering': ['component_type', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='BagAccessory',
        ),
    ]
