# Generated by Django 4.2.16 on 2026-07-25 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
        ('bag_making', '0003_remove_bagmakingcalculation_handle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('ZIPPER', 'Zipper'), ('HANDLE', 'Handle')], max_length=10)),
                ('weight_per_piece', models.FloatField(help_text='Weight in grams per piece')),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bagmakingcalculation',
            name='addon_type',
            field=models.CharField(choices=[('NONE', 'No Add-ons'), ('ZIPPER', 'Zipper Only'), ('HANDLES', 'Handles Only'), ('BOTH', 'Zipper and Handles')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='bagmakingcalculation',
            name='bag_type',
            field=models.CharField(choices=[('FLAT_SHEET', 'Flat Sheet Bag'), ('TUBULAR', 'Tubular Bag'), ('GUSSETED_SIDE', 'Side Gusseted Bag'), ('GUSSETED_BOTTOM', 'Bottom Gusseted Bag'), ('TUBULAR_WITH_FLAP', 'Tubular Bag with Flap'), ('LAMINATED_FLAT', 'Laminated Flat Bag'), ('LAMINATED_TUBULAR', 'Laminated Tubular Bag'), ('LAMINATED_GUSSETED_SIDE', 'Laminated Side Gusseted Bag'), ('LAMINATED_GUSSETED_BOTTOM', 'Laminated Bottom Gusseted Bag'), ('LAMINATED_TUBULAR_FLAP', 'Laminated Tubular with Flap')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bagmakingcalculation',
            name='calculation_type',
            field=models.CharField(choices=[('PIECES_WEIGHT', 'Pieces ↔ Weight'), ('PACKET_WEIGHT', 'Packet Weight'), ('BUNDLE_WEIGHT', 'Bundle/Bale Weight'), ('PRODUCTION_TIME', 'Production Time'), ('YIELD_EFFICIENCY', 'Yield & Efficiency')], max_length=20),
        ),
        migrations.DeleteModel(
            name='BagComponent',
        ),
        migrations.AddField(
            model_name='addoncomponent',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='bag_making.bagmakingcalculation'),
        ),
        migrations.AddField(
            model_name='addoncomponent',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial'),
        ),
    ]
