# Generated by Django 4.2.16 on 2026-07-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_making', '0004_addoncomponent_bagmakingcalculation_addon_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagmakingcalculation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='bagmakingcalculation',
            name='machine_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bagmakingcalculation',
            name='order_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
