# Generated by Django 4.2.16 on 2026-07-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_making', '0005_bagmakingcalculation_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagmakingcalculation',
            name='machine_name',
            field=models.CharField(blank=True, choices=[('SIDE_SEAL_01', 'Side Seal 01'), ('SIDE_SEAL_02', 'Side Seal 02'), ('SIDE_SEAL_03', 'Side Seal 03'), ('SIDE_SEAL_04', 'Side Seal 04'), ('SIDE_SEAL_05', 'Side Seal 05'), ('SIDE_SEAL_06', 'Side Seal 06'), ('SIDE_SEAL_07', 'Side Seal 07'), ('SIDE_SEAL_08', 'Side Seal 08'), ('SIDE_SEAL_09', 'Side Seal 09'), ('SIDE_SEAL_10', 'Side Seal 10'), ('SIDE_SEAL_11', 'Side Seal 11'), ('SIDE_SEAL_12', 'Side Seal 12'), ('SIDE_SEAL_13', 'Side Seal 13'), ('SIDE_SEAL_14', 'Side Seal 14'), ('SIDE_SEAL_15', 'Side Seal 15'), ('SIDE_SEAL_16', 'Side Seal 16'), ('SIDE_SEAL_17', 'Side Seal 17'), ('SIDE_SEAL_18', 'Side Seal 18'), ('SIDE_SEAL_19', 'Side Seal 19'), ('SIDE_SEAL_20', 'Side Seal 20'), ('SIDE_SEAL_21', 'Side Seal 21'), ('SIDE_SEAL_22', 'Side Seal 22'), ('SIDE_SEAL_23', 'Side Seal 23'), ('SIDE_SEAL_24', 'Side Seal 24'), ('SIDE_SEAL_25', 'Side Seal 25'), ('SIDE_SEAL_26', 'Side Seal 26'), ('SIDE_SEAL_27', 'Side Seal 27'), ('SIDE_SEAL_28', 'Side Seal 28'), ('SIDE_SEAL_29', 'Side Seal 29'), ('SIDE_SEAL_30', 'Side Seal 30'), ('SIDE_SEAL_31', 'Side Seal 31'), ('SIDE_SEAL_32', 'Side Seal 32'), ('SIDE_SEAL_33', 'Side Seal 33'), ('SIDE_SEAL_34', 'Side Seal 34'), ('SIDE_SEAL_35', 'Side Seal 35'), ('SIDE_SEAL_36', 'Side Seal 36'), ('SIDE_SEAL_37', 'Side Seal 37'), ('BOTTOM_SEAL_01', 'Bottom Seal 01'), ('BOTTOM_SEAL_02', 'Bottom Seal 02'), ('BOTTOM_SEAL_03', 'Bottom Seal 03'), ('BOTTOM_SEAL_04', 'Bottom Seal 04'), ('BOTTOM_SEAL_05', 'Bottom Seal 05'), ('BOTTOM_SEAL_06', 'Bottom Seal 06'), ('BOTTOM_SEAL_07', 'Bottom Seal 07'), ('BOTTOM_SEAL_08', 'Bottom Seal 08'), ('BOTTOM_SEAL_09', 'Bottom Seal 09'), ('BOTTOM_SEAL_10', 'Bottom Seal 10'), ('BOTTOM_SEAL_11', 'Bottom Seal 11'), ('BOTTOM_SEAL_12', 'Bottom Seal 12'), ('BOTTOM_SEAL_13', 'Bottom Seal 13'), ('BOTTOM_SEAL_14', 'Bottom Seal 14'), ('BOTTOM_SEAL_15', 'Bottom Seal 15'), ('BOTTOM_SEAL_16', 'Bottom Seal 16'), ('BOTTOM_SEAL_17', 'Bottom Seal 17'), ('BOTTOM_SEAL_18', 'Bottom Seal 18'), ('BOTTOM_SEAL_19', 'Bottom Seal 19'), ('POUCH_01', 'Pouch 01'), ('POUCH_02', 'Pouch 02'), ('POUCH_03', 'Pouch 03'), ('POUCH_04', 'Pouch 04'), ('POUCH_05', 'Pouch 05'), ('POUCH_06', 'Pouch 06'), ('FOLDER_01', 'Folder 01'), ('FOLDER_02', 'Folder 02'), ('FOLDER_03', 'Folder 03'), ('VEST_BAG_01', 'Vest Bag 01'), ('VEST_BAG_02', 'Vest Bag 02'), ('VEST_BAG_03', 'Vest Bag 03'), ('VEST_BAG_04', 'Vest Bag 04'), ('VEST_BAG_05', 'Vest Bag 05'), ('VEST_BAG_06', 'Vest Bag 06'), ('SPOUT_01', 'Spout 01'), ('SPOUT_02', 'Spout 02'), ('BREATHER_VENT_01', 'Breather/Vent 01'), ('BREATHER_VENT_02', 'Breather/Vent 02')], max_length=20, null=True),
        ),
    ]
