# Generated by Django 4.2.16 on 2026-08-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_making', '0006_alter_bagmakingcalculation_machine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoutGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "D Punch (30mm x 75mm)"', max_length=100)),
                ('geometry_type', models.CharField(help_text='Free-text category tag, e.g. "D_PUNCH" or "VEST_BAG" - used for grouping/filtering in the UI', max_length=50)),
                ('calibration_material', models.CharField(help_text='Material used when this geometry was calibrated', max_length=100)),
                ('density_g_cm3', models.FloatField(help_text='Density (rho) used at calibration - editable if confirmed later')),
                ('layers', models.IntegerField(default=2, help_text='Number of film layers (L) - normally 2')),
                ('area_cm2', models.FloatField(help_text='Stored, reusable effective area (A) - back-calculated once, then fixed')),
                ('calibration_thickness_um', models.FloatField(blank=True, help_text='Thickness used for the calibration sample, for reference', null=True)),
                ('calibration_mass_g', models.FloatField(blank=True, help_text='Measured sample mass used for the back-calculation, for reference', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['geometry_type', 'name'],
            },
        ),
    ]
