# Generated by Django 4.2.16 on 2026-08-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_making', '0007_cutoutgeometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g. "Grains & Cereals", "Powders", "Fertilizers & Chemicals", "Other"', max_length=50)),
                ('density_min_kg_m3', models.FloatField()),
                ('density_max_kg_m3', models.FloatField()),
                ('density_typical_kg_m3', models.FloatField(help_text='Midpoint of min/max - used as the default')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='bagmakingcalculation',
            name='bag_type',
            field=models.CharField(choices=[('FLAT_SHEET', 'Flat Sheet Bag'), ('TUBULAR', 'Tubular Bag'), ('GUSSETED_SIDE', 'Side Gusseted Bag'), ('GUSSETED_BOTTOM', 'Bottom Gusseted Bag'), ('TUBULAR_WITH_FLAP', 'Tubular Bag with Flap'), ('LAMINATED_FLAT', 'Laminated Flat Bag'), ('LAMINATED_TUBULAR', 'Laminated Tubular Bag'), ('LAMINATED_GUSSETED_SIDE', 'Laminated Side Gusseted Bag'), ('LAMINATED_GUSSETED_BOTTOM', 'Laminated Bottom Gusseted Bag'), ('LAMINATED_TUBULAR_FLAP', 'Laminated Tubular with Flap'), ('GUSSETED_BOTTOM_FLAP', 'Bottom Gusseted Bag with Flap'), ('LAMINATED_GUSSETED_BOTTOM_FLAP', 'Laminated Bottom Gusseted with Flap')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bagmakingcalculation',
            name='calculation_type',
            field=models.CharField(choices=[('PIECES_WEIGHT', 'Pieces ↔ Weight'), ('PACKET_WEIGHT', 'Packet Weight'), ('BUNDLE_WEIGHT', 'Bundle/Bale Weight'), ('PRODUCTION_TIME', 'Production Time'), ('YIELD_EFFICIENCY', 'Yield & Efficiency'), ('BAG_CAPACITY', 'Bag Fill Volume/Capacity'), ('ROLL_REQUIREMENT', 'Bags per Roll / Roll Requirement'), ('SEAL_STRENGTH', 'Heat Seal Strength')], max_length=20),
        ),
    ]
