# Generated by Django 4.2.16 on 2026-08-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('material_type', models.CharField(choices=[('FILM', 'Plastic Film'), ('INK', 'Ink'), ('SOLVENT', 'Solvent'), ('ADHESIVE', 'Adhesive'), ('HARDENER', 'Hardener')], max_length=20)),
                ('density', models.FloatField(help_text='Density in g/cm³')),
                ('is_ldpe', models.BooleanField(default=False, help_text='True if this material IS LDPE, or is a laminate whose sealing/inner layer is LDPE - used to gate accessories that require an LDPE sealing surface (zipper, spout assembly).')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DensityCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(help_text='Mass in grams')),
                ('volume', models.FloatField(help_text='Volume in cm³')),
                ('calculated_density', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
