# Generated by Django 4.2.16 on 2026-08-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticmaterial',
            name='is_ldpe',
            field=models.BooleanField(default=False, help_text='True if this material IS LDPE, or is a laminate whose sealing/inner layer is LDPE - used to gate accessories that require an LDPE sealing surface (zipper, spout assembly).'),
        ),
    ]
