# Generated by Django 4.2.16 on 2026-08-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InkFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ink_type', models.CharField(choices=[('PRIMARY', 'Primary (CMYK)'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary'), ('SPOT', 'Spot Color')], max_length=20)),
                ('base_color', models.CharField(blank=True, max_length=50)),
                ('pigment_percentage', models.FloatField(default=0.0)),
                ('binder_percentage', models.FloatField(default=0.0)),
                ('additives_percentage', models.FloatField(default=0.0)),
                ('solvent_percentage', models.FloatField(default=0.0)),
                ('density_g_cm3', models.FloatField(default=1.0)),
                ('coverage_gsm', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('FILM_MASS_LENGTH', 'Film Mass & Length'), ('INK_MASS', 'Ink Mass Needed'), ('MACHINE_SPEED', 'Machine Speed'), ('GSM_CALCULATION', 'GSM Calculation'), ('INK_MIXING', 'Ink Mixing'), ('PRODUCTION_TIME', 'Production Time'), ('ANILOX_COVERAGE', 'Anilox Ink Coverage'), ('DOT_GAIN_CONTRAST', 'Dot Gain / Print Contrast'), ('DELTA_E', 'Color Difference (Delta E)'), ('REGISTRATION_REPEAT', 'Registration / Repeat Length'), ('RESIDUAL_SOLVENT', 'Residual Solvent'), ('WASTE_ALLOWANCE', 'Waste Allowance Planning'), ('MAX_SAFE_SPEED', 'Max Safe Speed vs Drying'), ('CYLINDER_COVERAGE', 'Cylinder Coverage & Ink Consumption'), ('CYLINDER_WEAR_LIFE', 'Cylinder Wear & Life Planning')], max_length=20)),
                ('machine_name', models.CharField(blank=True, choices=[('FLEXO_F01', 'Flexo F01'), ('FLEXO_F02', 'Flexo F02'), ('FLEXO_F03', 'Flexo F03'), ('FLEXO_F04', 'Flexo F04'), ('FLEXO_F05', 'Flexo F05'), ('FLEXO_F06', 'Flexo F06'), ('FLEXO_F07', 'Flexo F07'), ('FLEXO_F08', 'Flexo F08'), ('FLEXO_F09', 'Flexo F09'), ('BFM_1', 'BFM 1'), ('BFM_2', 'BFM 2'), ('BFM_3', 'BFM 3'), ('ROTO_1', 'ROTO 1'), ('ROTO_2', 'ROTO 2'), ('ROTO_3', 'ROTO 3'), ('ROTO_4', 'ROTO 4'), ('ROTO_5', 'ROTO 5'), ('ROTO_6', 'ROTO 6')], max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('job_name', models.CharField(blank=True, max_length=150)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
