# Generated by Django 4.2.16 on 2026-07-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingcalculation',
            name='calculation_type',
            field=models.CharField(choices=[('FILM_MASS_LENGTH', 'Film Mass & Length'), ('INK_MASS', 'Ink Mass Needed'), ('MACHINE_SPEED', 'Machine Speed'), ('GSM_CALCULATION', 'GSM Calculation'), ('INK_MIXING', 'Ink Mixing'), ('PRODUCTION_TIME', 'Production Time'), ('ANILOX_COVERAGE', 'Anilox Ink Coverage'), ('DOT_GAIN_CONTRAST', 'Dot Gain / Print Contrast'), ('DELTA_E', 'Color Difference (Delta E)'), ('REGISTRATION_REPEAT', 'Registration / Repeat Length'), ('RESIDUAL_SOLVENT', 'Residual Solvent'), ('WASTE_ALLOWANCE', 'Waste Allowance Planning'), ('MAX_SAFE_SPEED', 'Max Safe Speed vs Drying')], max_length=20),
        ),
    ]
