# Generated by Django 4.2.16 on 2026-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_alter_printingcalculation_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingcalculation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='printingcalculation',
            name='job_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='printingcalculation',
            name='machine_name',
            field=models.CharField(blank=True, choices=[('FLEXO_F01', 'Flexo F01'), ('FLEXO_F02', 'Flexo F02'), ('FLEXO_F03', 'Flexo F03'), ('FLEXO_F04', 'Flexo F04'), ('FLEXO_F05', 'Flexo F05'), ('FLEXO_F06', 'Flexo F06'), ('FLEXO_F07', 'Flexo F07'), ('FLEXO_F08', 'Flexo F08'), ('FLEXO_F09', 'Flexo F09'), ('BFM_1', 'BFM 1'), ('BFM_2', 'BFM 2'), ('BFM_3', 'BFM 3'), ('ROTO_1', 'ROTO 1'), ('ROTO_2', 'ROTO 2'), ('ROTO_3', 'ROTO 3'), ('ROTO_4', 'ROTO 4'), ('ROTO_5', 'ROTO 5'), ('ROTO_6', 'ROTO 6')], max_length=20),
        ),
    ]
