# Generated by Django 4.2.16 on 2026-08-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaminatedStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('layers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('MATERIAL_COST_KG', 'Material Cost per kg'), ('MATERIAL_COST_METER', 'Material Cost per meter'), ('MATERIAL_COST_PIECE', 'Material Cost per piece'), ('ORDER_QUANTITY_KG', 'Order Quantity from kg'), ('ORDER_QUANTITY_METER', 'Order Quantity from meters'), ('ORDER_QUANTITY_PIECE', 'Order Quantity from pieces'), ('ROLL_COST', 'Roll Cost Calculation'), ('LAMINATED_COST', 'Laminated Material Cost'), ('MARGIN_MARKUP', 'Margin / Markup / Selling Price'), ('COST_PER_SQM', 'Cost per Square Meter'), ('BREAKEVEN_QTY', 'Breakeven Quantity'), ('VAT_CALCULATION', 'VAT Inclusive/Exclusive'), ('BULK_DISCOUNT', 'Bulk/Quantity-Break Discount')], max_length=25)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('order_name', models.CharField(blank=True, max_length=150)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesCalculationLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_kg', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('layer_order', models.IntegerField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='sales.salescalculation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
            ],
            options={
                'ordering': ['layer_order'],
            },
        ),
    ]
