# Generated by Django 4.2.16 on 2026-07-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescalculation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salescalculation',
            name='order_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='salescalculation',
            name='calculation_type',
            field=models.CharField(choices=[('MATERIAL_COST_KG', 'Material Cost per kg'), ('MATERIAL_COST_METER', 'Material Cost per meter'), ('MATERIAL_COST_PIECE', 'Material Cost per piece'), ('ORDER_QUANTITY_KG', 'Order Quantity from kg'), ('ORDER_QUANTITY_METER', 'Order Quantity from meters'), ('ORDER_QUANTITY_PIECE', 'Order Quantity from pieces'), ('ROLL_COST', 'Roll Cost Calculation'), ('LAMINATED_COST', 'Laminated Material Cost'), ('MARGIN_MARKUP', 'Margin / Markup / Selling Price'), ('COST_PER_SQM', 'Cost per Square Meter'), ('BREAKEVEN_QTY', 'Breakeven Quantity'), ('VAT_CALCULATION', 'VAT Inclusive/Exclusive'), ('BULK_DISCOUNT', 'Bulk/Quantity-Break Discount')], max_length=25),
        ),
        migrations.CreateModel(
            name='SalesCalculationLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_kg', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('layer_order', models.IntegerField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='sales.salescalculation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
            ],
            options={
                'ordering': ['layer_order'],
            },
        ),
    ]
